name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Project install
        uses: cypress-io/github-action@v2
        with:
          build: npm install
          runTests: false
      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

  api-tests:
      timeout-minutes: 15
      runs-on: ubuntu-latest
      container: cypress/browsers:node12.18.3-chrome87-ff82
      needs: install
      strategy:
        fail-fast: false
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: actions/cache@v2
          id: yarn-and-build-cache
          with:
            path: |
              ~/.cache/Cypress
              build
              node_modules
            key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-node_modules-build-

        - name: "Tests - Api"
          uses: cypress-io/github-action@v2
          with:            
            install: false
            start: yarn start:ci
            build: npm install
            wait-on: "http://localhost:3000"
            wait-on-timeout: 120
            browser: chrome
            spec: cypress/tests/api/api-notifications.spec.ts
            config-file: rp-cypress-api.json
        - name: Sleep for 20s
          uses: juliangruber/sleep-action@v1
          with:
           time: 20s        

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: npm install
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/tests/ui/notifications.spec.ts
          config-file: rp-cypress-chrome.json
      - name: Sleep for 20s
        uses: juliangruber/sleep-action@v1
        with:
          time: 20s   

  ui-chrome-mobile-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: "UI Tests - Chrome - Mobile"
        uses: cypress-io/github-action@v2
        with:
          build: npm install
          install: false
          config: "viewportWidth=375,viewportHeight=667"
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/tests/ui/notifications.spec.ts
          config-file: rp-cypress-chrome-mobile.json
      - name: Sleep for 20s
        uses: juliangruber/sleep-action@v1
        with:
          time: 20s  

  ui-firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.18.3-chrome87-ff82
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v2
        with:
          build: npm install
          install: false
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: firefox
          spec: cypress/tests/ui/notifications.spec.ts
          config-file: rp-cypress-firefox.json
      - name: Sleep for 20s
        uses: juliangruber/sleep-action@v1
        with:
          time: 20s  

  ui-firefox-tests-mobile:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.18.3-chrome87-ff82
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: "UI Tests - Firefox - Mobile"
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: npm install
          config: "viewportWidth=375,viewportHeight=667"
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: firefox
          spec: cypress/tests/ui/notifications.spec.ts
          config-file: rp-cypress-firefox-mobile.json
      - name: Sleep for 20s
        uses: juliangruber/sleep-action@v1
        with:
          time: 20s  
