name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"
  pull_request:
    branches:
      - "develop"

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress_Cache
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      # report machine parameters
      - run: yarn cypress info
      - run: node -p 'os.cpus()'
      - run: yarn types
      - run: yarn test:unit:ci
      - run: yarn build:ci

  ui-api-tests:
      timeout-minutes: 15
      runs-on: ubuntu-latest
      container: cypress/browsers:node12.18.3-chrome87-ff82
      needs: install
      strategy:
        fail-fast: false
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: actions/cache@v2
          id: yarn-and-build-cache
          with:
            path: |
              ~/.cache/Cypress
              build
              node_modules
            key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-node_modules-build-

        - name: "UI Tests - Api"
          run:  npx cypress run --spec "cypress/tests/api/api-transactions.spec.ts" --browser chrome